<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyName>YoutubeMp3.Editor</AssemblyName>
        <RootNamespace>YoutubeMp3.Editor</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.*" />
        <PackageReference Include="NAudio" Version="2.2.1" />
        <PackageReference Include="NAudio.Lame" Version="2.1.0" />
    </ItemGroup>
</Project>
